Controllers/CargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Storage;
using Microsoft.Azure.Storage.Blob;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using miniwms.Data;
using miniwms.Models;
using Microsoft.Extensions.Configuration;
using System.Configuration;

// namespace - helps organize projects, helps control scopes
namespace miniwms.Controllers
{
    // public class - no restrictions on access CargoController - name
    // Controller - class we're stating from the MVC
    // C# has classical inheritance. that's the  " : " between CargoController & Controller.
    // Controllers do a whole bunch of stuff and we are inheriting all that functionality.
    public class CargoController : Controller
    {
        // private readonly he benefit is that you can't inadvertently change it from
        //another part of that class after it is initialized.
        //Possible to get an example on the above???
        private readonly ApplicationDbContext _context;

        private readonly ILogger<CargoController> _logger;

        private readonly IConfiguration _configuration;


        private CloudBlobContainer container;

        //CargoController(ApplicationDbContext)
        // a little confusing syntax wise but assuming it's
        // reassigning ApplicationDbContext into _context
        // Dependency Injection - Specific to dot net MVC - any parameters put into the constructor are depedencies.
        // It's saying "hey I need to use this"
        public CargoController(
            ApplicationDbContext context,
            ILogger<CargoController> logger,
            IConfiguration configuration
        )
        {
            _context = context;
            _logger = logger;
            _configuration = configuration;
        }

        // GET: Cargo
        public async Task<IActionResult>
        Index() // when someone makes a request to our server, an <IActionResult> is returned.
        {
            // Get request when going to Cargo
            // return the View, but in the parameters of the view function
            // we're awaiting the DB query to execute
            _logger.LogWarning("testing 1 2 3", null);

            return View(await _context
                .Cargo // go to Db.Cargo
                .Include(Cargo => (Cargo.Shipment)) //Include Cargo.Shipment (ID)
                .ToListAsync()); // generates list
        }

        // GET: Cargo/Details/5
        public async Task<IActionResult>
        Details(int? id) // Details takes an integer (id) so we can look up the specific cargo by that number // public async Task immediately tells this method will be asynchronous
        {
            if (
                id == null // if the number is null or not found - return a view of NotFound()
            )
            {
                return NotFound();
            }

            // set our variable of cargo -> then query the DB and see if can find via the id number
            Cargo cargo =
                await _context
                    .Cargo
                    .Include(Cargo => (Cargo.Urls))
                    .FirstOrDefaultAsync(m => m.Id == id);
            if (cargo == null)
            {
                return NotFound(); // if not found, same as above
            }

            return View(cargo); // otherwise return the view with our cargo parameter
        }




        // GET: Cargo/Create
        public async Task<IActionResult>
        Create() // public async tells us this will be async - and we're in the Create controller now
        {
            var shipmentList = await _context.Shipment.ToListAsync(); // querying db for our shipment list
            ViewBag.shipmentList = shipmentList;

            var customerList = await _context.Customer.ToListAsync(); // querying db for customer list
            ViewBag.customerList = customerList;

            return View(); // returning the view of Create but now we have access to data to use in the HTML (i.e. delegating cargo to a certain shipment)
        }

        // POST: Cargo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost] // methods of posting client data or form data to the server.
        [ValidateAntiForgeryToken] //  to prevent cross-site request forgery attacks
        public async Task<IActionResult>
        Create(
            [
                Bind(
                    "Id,TypeOfPallet,ProNumber,Length,Width,Height,Weight,Damage,Shipment,Customer,PieceCount,Destination,ArrivingFrom,LotNumber,Consignee,Marks")
            ]
            Cargo cargo
        ) // Bindings .... ?
        {
            if (
                ModelState.IsValid // ModelState.IsValid indicates if it was possible to bind the incoming values
            )
            // from the request to the model correctly and whether any explicitly specified
            // validation rules were broken during the model binding process.
            {
                var shipment =
                    await _context.Shipment.FindAsync(cargo.Shipment.Id);

                // modify cargo shipment to be this new shipment that we looked up in the DB
                cargo.Shipment = shipment;

                // await _context.SaveChangesAsync(); // wait for our database to save the above changes
                var customer =
                    await _context.Customer.FindAsync(cargo.Customer.Id);
                cargo.Customer = customer;
                _context.Add (cargo);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index)); // returns us to the Index page of cargo when done
            }
            return View(cargo); // sets up the view for entering data
        }

        [HttpPost] // post method
        [AllowAnonymous]
        // this will allow anyone to ping the server (good for postman)
        public async Task<IActionResult>
        CreateByAPI(
            [FromBody] int Id,
            PalletType TypeOfPallet,
            double Length,
            double Width,
            double Height,
            double Weight,
            bool Damage,
            Shipment Shipment,
            Customer Customer
        ) // The above model is what we should be expecting in raw JSON format
        {
            if (
                ModelState.IsValid // If the model is good we can proceed to the below code
            )
            {
                var shipment = await _context.Shipment.FindAsync(Shipment.Id); // set shipment = to ShipmentId in the DB

                // modify cargo shipment to be this new shipment that we looked up in the DB
                // Shipment = shipment;
                //_context.Add (cargo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return Ok("Succeeded"); // send back Succeeded as a response
        }

        // GET: Cargo/Edit/5
        public async Task<IActionResult>
        Edit(int? id) // very similar to above already explained!
        {
            var shipmentList = await _context.Shipment.ToListAsync(); // querying db for our shipment list
            ViewBag.shipmentList = shipmentList;

            var customerList = await _context.Customer.ToListAsync(); // querying db for customer list
            ViewBag.customerList = customerList;

            if (id == null)
            {
                return NotFound();
            }

            var cargo = await _context.Cargo.FindAsync(id);
            if (cargo == null)
            {
                return NotFound();
            }
            return View(cargo);
        }

        // POST: Cargo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        // whenever someone is sending data to our server - we want to make sure they're coming from 'our website'
        // dot net core is constantly doing a crypto exchange with the browser - we just have to remember to validate the antiforgerytoken
        // any time we're taking info from the browser.
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
        Edit(
            int id,
            [Bind("Id,TypeOfPallet,Length,Width,Height,Weight,Damage,Shipment")]
            Cargo cargo
        )
        {
            if (id != cargo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                // if the Model is good - update the DB with cargo
                // Are update & SaveChanges not kind of the same though? Why both?
                {
                    _context.Update (cargo);
                    await _context.SaveChangesAsync();
                }
                catch (
                    DbUpdateConcurrencyException // read up on this, still not 100%
                )
                // sounds similar to JS catch method
                {
                    if (!CargoExists(cargo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cargo);
        }
 
        // POST - Post Photo
        [HttpPost] // post method
        // this will allow anyone to ping the server (good for postman)
        public async Task<IActionResult>

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using miniwms.Data;
using miniwms.Models;

namespace miniwms.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomerController(ApplicationDbContext context)
        {
            // naming convention either lower case for private variable or an underscore before it. 
            _context = context;
        }

        // GET: Customer
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customer.ToListAsync());
        }

        // GET: Customer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customer/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CustomerName,Country,Email,Phone,Address,LicenseActive")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customer/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CustomerName,Country,Email,Phone,Address,LicenseActive")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customer/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customer.FindAsync(id);
            _context.Customer.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customer.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - miniwms</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
     @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">miniwms</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cargo" asp-action="Index">Cargo</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cargo" asp-action="Create">CreateCargo</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Customer" asp-action="Create">New Customer</a>
                        </li>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Shipment" asp-action="Index">Shipment</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - miniwms - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>