Controllers/CargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Storage;
using Microsoft.Azure.Storage.Blob;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using miniwms.Data;
using miniwms.Models;
using Microsoft.Extensions.Configuration;
using System.Configuration;

// namespace - helps organize projects, helps control scopes
namespace miniwms.Controllers
{
    // public class - no restrictions on access CargoController - name
    // Controller - class we're stating from the MVC
    // C# has classical inheritance. that's the  " : " between CargoController & Controller.
    // Controllers do a whole bunch of stuff and we are inheriting all that functionality.
    public class CargoController : Controller
    {
        // private readonly he benefit is that you can't inadvertently change it from
        //another part of that class after it is initialized.
        //Possible to get an example on the above???
        private readonly ApplicationDbContext _context;

        private readonly ILogger<CargoController> _logger;

        private readonly IConfiguration _configuration;


        private CloudBlobContainer container;

        //CargoController(ApplicationDbContext)
        // a little confusing syntax wise but assuming it's
        // reassigning ApplicationDbContext into _context
        // Dependency Injection - Specific to dot net MVC - any parameters put into the constructor are depedencies.
        // It's saying "hey I need to use this"
        public CargoController(
            ApplicationDbContext context,
            ILogger<CargoController> logger,
            IConfiguration configuration
        )
        {
            _context = context;
            _logger = logger;
            _configuration = configuration;
        }

        // GET: Cargo
        public async Task<IActionResult>
        Index() // when someone makes a request to our server, an <IActionResult> is returned.
        {
            // Get request when going to Cargo
            // return the View, but in the parameters of the view function
            // we're awaiting the DB query to execute
            _logger.LogWarning("testing 1 2 3", null);

            return View(await _context
                .Cargo // go to Db.Cargo
                .Include(Cargo => (Cargo.Shipment)) //Include Cargo.Shipment (ID)
                .ToListAsync()); // generates list
        }

        // GET: Cargo/Details/5
        public async Task<IActionResult>
        Details(int? id) // Details takes an integer (id) so we can look up the specific cargo by that number // public async Task immediately tells this method will be asynchronous
        {
            if (
                id == null // if the number is null or not found - return a view of NotFound()
            )
            {
                return NotFound();
            }

            // set our variable of cargo -> then query the DB and see if can find via the id number
            Cargo cargo =
                await _context
                    .Cargo
                    .Include(Cargo => (Cargo.Urls))
                    .FirstOrDefaultAsync(m => m.Id == id);
            if (cargo == null)
            {
                return NotFound(); // if not found, same as above
            }

            return View(cargo); // otherwise return the view with our cargo parameter
        }




        // GET: Cargo/Create
        public async Task<IActionResult>
        Create() // public async tells us this will be async - and we're in the Create controller now
        {
            var shipmentList = await _context.Shipment.ToListAsync(); // querying db for our shipment list
            ViewBag.shipmentList = shipmentList;

            var customerList = await _context.Customer.ToListAsync(); // querying db for customer list
            ViewBag.customerList = customerList;

            return View(); // returning the view of Create but now we have access to data to use in the HTML (i.e. delegating cargo to a certain shipment)
        }

        // POST: Cargo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost] // methods of posting client data or form data to the server.
        [ValidateAntiForgeryToken] //  to prevent cross-site request forgery attacks
        public async Task<IActionResult>
        Create(
            [
                Bind(
                    "Id,TypeOfPallet,ProNumber,Length,Width,Height,Weight,Damage,Shipment,Customer,PieceCount,Destination,ArrivingFrom,LotNumber,Consignee,Marks")
            ]
            Cargo cargo
        ) // Bindings .... ?
        {
            if (
                ModelState.IsValid // ModelState.IsValid indicates if it was possible to bind the incoming values
            )
            // from the request to the model correctly and whether any explicitly specified
            // validation rules were broken during the model binding process.
            {
                var shipment =
                    await _context.Shipment.FindAsync(cargo.Shipment.Id);

                // modify cargo shipment to be this new shipment that we looked up in the DB
                cargo.Shipment = shipment;

                // await _context.SaveChangesAsync(); // wait for our database to save the above changes
                var customer =
                    await _context.Customer.FindAsync(cargo.Customer.Id);
                cargo.Customer = customer;
                _context.Add (cargo);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index)); // returns us to the Index page of cargo when done
            }
            return View(cargo); // sets up the view for entering data
        }

        [HttpPost] // post method
        [AllowAnonymous]
        // this will allow anyone to ping the server (good for postman)
        public async Task<IActionResult>
        CreateByAPI(
            [FromBody] int Id,
            PalletType TypeOfPallet,
            double Length,
            double Width,
            double Height,
            double Weight,
            bool Damage,
            Shipment Shipment,
            Customer Customer
        ) // The above model is what we should be expecting in raw JSON format
        {
            if (
                ModelState.IsValid // If the model is good we can proceed to the below code
            )
            {
                var shipment = await _context.Shipment.FindAsync(Shipment.Id); // set shipment = to ShipmentId in the DB

                // modify cargo shipment to be this new shipment that we looked up in the DB
                // Shipment = shipment;
                //_context.Add (cargo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return Ok("Succeeded"); // send back Succeeded as a response
        }

        // GET: Cargo/Edit/5
        public async Task<IActionResult>
        Edit(int? id) // very similar to above already explained!
        {
            var shipmentList = await _context.Shipment.ToListAsync(); // querying db for our shipment list
            ViewBag.shipmentList = shipmentList;

            var customerList = await _context.Customer.ToListAsync(); // querying db for customer list
            ViewBag.customerList = customerList;

            if (id == null)
            {
                return NotFound();
            }

            var cargo = await _context.Cargo.FindAsync(id);
            if (cargo == null)
            {
                return NotFound();
            }
            return View(cargo);
        }

        // POST: Cargo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        // whenever someone is sending data to our server - we want to make sure they're coming from 'our website'
        // dot net core is constantly doing a crypto exchange with the browser - we just have to remember to validate the antiforgerytoken
        // any time we're taking info from the browser.
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
        Edit(
            int id,
            [Bind("Id,TypeOfPallet,Length,Width,Height,Weight,Damage,Shipment")]
            Cargo cargo
        )
        {
            if (id != cargo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                // if the Model is good - update the DB with cargo
                // Are update & SaveChanges not kind of the same though? Why both?
                {
                    _context.Update (cargo);
                    await _context.SaveChangesAsync();
                }
                catch (
                    DbUpdateConcurrencyException // read up on this, still not 100%
                )
                // sounds similar to JS catch method
                {
                    if (!CargoExists(cargo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cargo);
        }
 
        // POST - Post Photo
        [HttpPost] // post method
        // this will allow anyone to ping the server (good for postman)
        public async Task<IActionResult>

Controllers/ShipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using miniwms.Data;
using miniwms.Models;
using Microsoft.AspNetCore.Authorization;

namespace miniwms.Controllers
{
    public class ShipmentController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShipmentController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Shipment
        public async Task<IActionResult> Index()
        {
            return View(await _context.Shipment.ToListAsync());
        }

        // GET: Shipment/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var cargoList = await _context.Cargo.ToListAsync();
            ViewBag.cargoList = cargoList;

            var customerList = await _context.Customer.ToListAsync();
            ViewBag.customerList = customerList;

            var shipment = await _context.Shipment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shipment == null)
            {
                return NotFound();
            }

            return View(shipment);
        }

        // GET: Shipment/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shipment/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ContainerNumber,ShipmentNumber,NumberOfItems,TotalWeight,TotalVolume,ShipmentReceived")] Shipment shipment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shipment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shipment);
        }

        // POST TEST - Shipment via Postman
        [HttpPost]
        [AllowAnonymous]

        public async Task<IActionResult>

        CreateByAPI(
            Shipment shipment
        )
        {
            if (ModelState.IsValid)
            {
                _context.Add(shipment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return Ok("Sucessful Shipment Post");
        }

        // GET: Shipment/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shipment = await _context.Shipment.FindAsync(id);
            if (shipment == null)
            {
                return NotFound();
            }
            return View(shipment);
        }

        // POST: Shipment/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ContainerNumber,ShipmentNumber,NumberOfItems,TotalWeight,TotalVolume,ShipmentReceived")] Shipment shipment)
        {
            if (id != shipment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shipment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShipmentExists(shipment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shipment);
        }

        // GET: Shipment/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shipment = await _context.Shipment
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shipment == null)
            {
                return NotFound();
            }

            return View(shipment);
        }

        // POST: Shipment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shipment = await _context.Shipment.FindAsync(id);
            _context.Shipment.Remove(shipment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShipmentExists(int id)
        {
            return _context.Shipment.Any(e => e.Id == id);
        }
    }
}

Views/Cargo/Create.cshtml
@model miniwms.Models.Cargo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cargo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TypeOfPallet" class="control-label"></label>
                <select asp-for="TypeOfPallet" class="form-control">
                @foreach (string TypeOfPallet in Enum.GetNames(typeof(PalletType)))
                    {
                        <option>@TypeOfPallet</option>
                    }
                </select>
                <span asp-validation-for="TypeOfPallet" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="ProNumber" class="control-label"></label>
                <input asp-for="ProNumber" class="form-control" />
                <span asp-validation-for="ProNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Length" class="control-label"></label>
                <input asp-for="Length" class="form-control" />
                <span asp-validation-for="Length" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height" class="control-label"></label>
                <input asp-for="Height" class="form-control" />
                <span asp-validation-for="Height" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Weight" class="control-label"></label>
                <input asp-for="Weight" class="form-control" />
                <span asp-validation-for="Weight" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Damage" /> @Html.DisplayNameFor(model => model.Damage)
                </label>
            </div>
                   <div class="form-group">
                <label asp-for="Shipment.Id" class="control-label">Shipment ID</label>
                <select asp-for="Shipment.Id" class="form-control">
                @foreach (Shipment Shipment in ViewBag.shipmentList)
                    {
                        <option value="@Shipment.Id">@Shipment.ShipmentNumber</option>
                    }
                </select>
                <span asp-validation-for="Shipment.Id" class="text-danger"></span>
            </div>
              
                   <div class="form-group">
                <label asp-for="Customer.Id" class="control-label">Customer</label>
                <select asp-for="Customer.Id" class="form-control">
                @foreach (Customer Customer in ViewBag.customerList)
                    {
                        <option value="@Customer.Id">@Customer.CustomerName</option>
                    }
                </select>
                <span asp-validation-for="Customer.Id" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="PieceCount" class="control-label"></label>
                <input asp-for="PieceCount" class="form-control" />
                <span asp-validation-for="PieceCount" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="ArrivingFrom" class="control-label"></label>
                <input asp-for="ArrivingFrom" class="form-control" />
                <span asp-validation-for="ArrivingFrom" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="LotNumber" class="control-label"></label>
                <input asp-for="LotNumber" class="form-control" />
                <span asp-validation-for="LotNumber" class="text-danger"></span>
            </div>  
            <div class="form-group">
                <label asp-for="Consignee" class="control-label"></label>
                <input asp-for="Consignee" class="form-control" />
                <span asp-validation-for="Consignee" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="Marks" class="control-label"></label>
                <input asp-for="Marks" class="form-control" />
                <span asp-validation-for="Marks" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Cargo/Delete.cshtml
@model miniwms.Models.Cargo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cargo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfPallet)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfPallet)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Length)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Length)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Damage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Damage)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Cargo/Details.cshtml
@model miniwms.Models.Cargo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cargo</h4>
    <hr />
    <div class="col-sm-2">
        <a asp-action="GetPicture" asp-route-id="@Model.Id">
            <input type="submit" value="Add Picture" class="btn btn-outline-primary" />
        </a>
    </div>
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfPallet)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TypeOfPallet)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Length)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Length)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Height)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Height)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Weight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Damage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Damage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PieceCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PieceCount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ArrivingFrom)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ArrivingFrom)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LotNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LotNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marks)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marks)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Urls)
        </dt>
        <dd>
            <div class="row">
                @foreach (var urlPath in Model.Urls)
                {
                    <div class="col">
                        <div class="card mt-5" style="width: 18rem;">
                            <img src="@urlPath.Url" class="card-img-top" alt="Cargo Photo">
                            <div class="card-body">
                                <p class="card-text">Some quick example text to build on the card title and make up the bulk
                                    of the card's content.</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>

</div>

Views/Cargo/GetPicture.cshtml
@model miniwms.Models.Cargo

@{
    ViewData["Title"] = "Create";
}

<h1>Retrieving</h1>

<h4>Picture</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="PostPicture" asp-route-id="@Model.Id" enctype="multipart/form-data">
            <input type="hidden" value="@Model.Id" name="Id"/>
            <div class="form-group">
                <input type="file" name="PictureFile"/> 
            </div>
     
          
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Cargo/Index.cshtml
@model IEnumerable<miniwms.Models.Cargo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TypeOfPallet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Length)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Damage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Shipment)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TypeOfPallet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Length)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Width)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Height)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Damage)
                </td>

                <td>
                    @if (item.Shipment != null)
                    {
                        <a asp-controller="Shipment" asp-action="Details" asp-route-id="@item.Shipment.Id">
                            @Html.DisplayFor(modelItem => item.Shipment.ShipmentNumber)
                        </a>
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>